### ISSUE TITLE
communicate by UCI with engine in Nim

### ISSUE THREAD

**Issue by tissatussa** [tsoj/Nalwald#3]
i tried to create a Nim script to do this with a (one) thread, but my code is not complete and probably wrong .. since you code Nim, can you take a look at my lines ? : [run.zip](https://github.com/user-attachments/files/17189723/run.zip)

catching output and giving commands might be easy to accomplish, but various techniques seem involved and i'm stuck .. i just want to concentrate on handling the output of an UCI engine when evaluating, also with MultiPV, and writing a GUI for it - at this stage i want to use 'wxnim' for that.

btw. nice story of Nalwald, also those "noteworthy features" !

**Comment by tsoj** [comment]
I'm not very familiar with Nim GUI development. The thing that makes this problem non-trivial is that for UCI you need to handle the output of the engine at the same time as giving input to it. So you need one thread for reading the output stream, and one thread writing command into the input stream (e.g. `stop`, `isready`, `quit`).

If you want to use wxnim, best refer to https://github.com/PMunch/wxnim?tab=readme-ov-file#running-work-on-background-threads ("long running tasks" would be your engine that is running) how to do multithreading with the GUI.

If you're not very familiar with programming I suggest that you either start with an easier project, and/or use Python. With Python ChatGPT can help much better than with Nim.

If you are determined to use Nim, a better place to ask such questions is the Nim Discord: https://discord.com/invite/nim or the Nim forum: https://forum.nim-lang.org/

**Comment by tissatussa** [comment]
thanks for this info, i really appreciate it !
